version: "3.4"

services:
  jupyterlab:
    image: invariant_pub
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    entrypoint:
      - jupyter
      - lab
      - --allow-root
